### ISSUE TITLE
wrong cmd command for undind

### ISSUE THREAD

**Issue by abogdanovich** [Sicness/pyNooLite#2]
unbind не работает, неверно указана команда.

0x0f > 16 значение=15 – сообщает исполнительному устройству, что
управляющее хочет записать свой адрес в его память

надо 

значение=9 – запускает процедуру стирания адреса
управляющего устройства из памяти исполнительного

9 = 0x09

и заменить строки
################################
def unbind(self, ch):
        """ Send unbind signal on channel
        First channal is 0 """
        self._cmd = self._init_command
        self._cmd[1] = 0x0f       # "unbind" command
        if self._set_ch(ch):
            return -2
        return self._send()
################################

        self._cmd[1] = 0x09       # "unbind" command

**Comment by Sicness** [comment]
Здравствуйте.
Если Вам не трудно и хочется пофиксить, пожалуйста найдите это в документации и сделайте pull request, я вмержу.

**Comment by abogdanovich** [comment]
done. thanks!
